### ISSUE TITLE
bug: several warnings & fails in official install process

### ISSUE THREAD

**Issue by avczar** [swiftwave-org/swiftwave#1336]
### Describe the bug

Fresh Debian 13 installation done, then I'm running the installation sequence directly:

1. su -
2. apt install sudo
3. sudo usermod -aG sudo master
4. exit + exit (re-login)
5. sudo apt update -y
6. sudo apt install curl git unzip tar **gpg** -y (gpg is missing in step 2 of official doc)
7. curl -fsSL https://get.docker.com | sudo bash -
> Usual warning about run as non-root user: https://i.goopics.net/sv59ag.jpg
8. sudo mkdir -p /etc/apt/keyrings
9. sudo mkdir /root/.gnupg
10. sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/swiftwave.gpg --keyserver keyserver.ubuntu.com --recv-keys DD510C86CD3F6764
> Warning about local keyring safety (I dont know why): https://i.goopics.net/k60v53.jpg (line 2)
11. echo "deb [signed-by=/etc/apt/keyrings/swiftwave.gpg] http://deb.repo.swiftwave.org/ swiftwave stable" | sudo tee /etc/apt/sources.list.d/swiftwave.list
12. sudo apt update -y
> Fail: https://i.goopics.net/k60v53.jpg

I retried 2 times, and same result each time.

Thanks for help.

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
> Warning about local keyring safety (I dont know why): [i.goopics.net/k60v53.jpg](https://i.goopics.net/k60v53.jpg) (line 2)

Based on the image, it looks like the key hasn't been downloaded correctly.
Try again to download the key and also do check the file, if it's blank.

We use ubuntu keyserver for fetching the PGP keys, so it shouldn't be an issue until unless your network provider blocking HKP Protocol or something.

```
sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/swiftwave.gpg --keyserver keyserver.ubuntu.com --recv-keys DD510C86CD3F6764
```

If this not working correcting, try another keyserver

```
sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/swiftwave.gpg --keyserver keys.openpgp.org  --recv-keys DD510C86CD3F6764
```

**Comment by avczar** [comment]
Hi,

Same with keys.openpgp.org, but after new full install of Debian 13 and a network interface change. This time, seems no warn about repo safety, but can't still properly establish SSL connection to your server: "Download of some index files failed, so ignored, old ones use instead" (https://i.goopics.net/usm8i6.jpg)
I tried to install anyway in next step (sudo apt install swiftwave -y), but "impossible to find swiftwave."

I installed successful Dokploy, Coolify, CasaOS and Cosmos in other similar VMs (PVE9) with same config and Debian 13 too; I didn't have any problem with.

Thanks again.

**Comment by avczar** [comment]
I retested with Debian 13.1 minimal (like previously, w/o any module/desktop env), with getting key from ubuntu.com or openpgp.org, I'm always blocked at the same point, just before install swiftwave. Your repo seems not properly signed, or you have integrity problem w/ your signature key... Even `gpg --decrypt` doesn't work (each time, from each source), as you can see (output translation: no proper/correct data found): https://i.goopics.net/naosip.jpg
I did not make any copy and paste, every command was typed by hand each time.

---

And in doc, you should be more specific by fix and complete the instructions:
```
sudo apt install curl git unzip tar gpg -y
...
sudo mkdir -p /etc/apt/keyrings
sudo chmod 755 /etc/apt/keyrings
sudo mkdir /root/.gnupg
sudo chmod 700 /root/.gnupg
```

**Comment by avczar** [comment]
I retested with Debian 13.1 minimal (like previously, w/o any module/desktop env), with getting key from ubuntu.com or openpgp.org, I'm always blocked at the same point, just before install swiftwave. Your repo seems not properly signed, or maybe integrity problem w/ your signature key... I did not make any copy and paste, every command was typed by hand each time (VM).
Check: https://i.goopics.net/naosip.jpg | Wrong last command to check gpg, fixed here: https://i.goopics.net/mbvb8t.jpg

---

And in doc, you should be more specific by fix and complete the instructions:
```
sudo apt install curl git unzip tar gpg -y
...
sudo mkdir -p -m 0755 /etc/apt/keyrings
sudo chmod 0644 /etc/apt/keyrings/*.gpg
sudo chown -R root:root /etc/apt/keyrings
sudo mkdir -m 0700 /root/.gnupg
```

**Comment by tanmoysrt** [comment]
I use Ubuntu 22.04/24.04 and never faced any issue like that before, maybe there are some security hardening on other os.
Raise a PR here - https://github.com/swiftwave-org/swiftwave.org for adding the extra setup steps.

**Comment by avczar** [comment]
Ubuntu 24.04 is still fairly tolerant about repositories sign/auth method, whereas Debian 13 already applies latest security rules in state-of-the-art. This will change in the next version of Ubuntu, so you will need to adapt your repo sooner or later to comply with the new requirements.

**Comment by Richardswe** [comment]
Just for info. This still exists. I tried to install Swiftwave in a Debian 13 LXC on PVE:9.1.2 
" Warning: OpenPGP signature verification failed: http://deb.repo.swiftwave.org swiftwave InRelease: Sub-process /usr/bin/sqv returned an error code (1), error message is: Error: Failed to parse keyring "/etc/apt/keyrings/swiftwave.gpg"  Caused by:     0: Reading "/etc/apt/keyrings/swiftwave.gpg": EOF     1: EOF
Error: The repository 'http://deb.repo.swiftwave.org swiftwave InRelease' is not signed.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
 "

**Comment by avczar** [comment]
@Richardswe Unfortunately, this issue is probably visible tip of the iceberg. Personally, I can risk to using this in production mode even for homelab. I tested many another solutions, some good, and my pre-final choice used since about 4 months is 1papel: effectively reliable, seems secure (ACPw w/ many ACL) and easy to use for compose stacks. I recommend considering other PaaS.

**Comment by nerometa** [comment]
I have the same problem on freshly installed Debian 13

**Comment by peter-vanpoucke** [comment]
Looks like the key needs to be in the Sequoia PGP format for Debian 13 (found [here](https://github.com/grafana/k6/issues/5205#issuecomment-3395344971) and [here](https://share.google/aimode/DyNAq2hRQxvMHG6QT)).
So (with the help [from avczar](https://github.com/swiftwave-org/swiftwave/issues/1336#issuecomment-3304520336)) this did it for me :
```bash
sudo apt install curl git unzip tar gpg -y
sudo mkdir -p -m 0755 /etc/apt/keyrings
sudo chmod 0644 /etc/apt/keyrings/*.gpg
sudo chown -R root:root /etc/apt/keyrings
sudo mkdir -m 0700 /root/.gnupg

sudo gpg --keyserver keyserver.ubuntu.com --recv-keys DD510C86CD3F6764
sudo gpg --export DD510C86CD3F6764 | sudo gpg --dearmor -o /etc/apt/keyrings/swiftwave.gpg

echo "deb [signed-by=/etc/apt/keyrings/swiftwave.gpg] http://deb.repo.swiftwave.org/ swiftwave stable" | sudo tee /etc/apt/sources.list.d/swiftwave.list

sudo apt update -y
```

Hope the installation is fine now 🤞.
